## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Import Dataset

In [3]:
df = pd.read_csv("insurance.csv")

## Top & Bottom Records

In [5]:
df.head()
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

## Shape

In [6]:
df.shape

(1338, 7)

## Dataset information

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 94.5 KB

## Statistical Summary

In [9]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

## Check Missing Values
### Findings
- No missing values found in the dataset

In [11]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

## Check Duplicate Records

In [12]:
df.duplicated().sum()

np.int64(1)

## Age Column Analysis

In [19]:
df["age"].describe()

df["age"].unique()

array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
       59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
       20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39])

## Sex Column Analysis

In [21]:
df["sex"].value_counts()

sex
male      675
female    662
Name: count, dtype: int64

## BMI Column Analysis

In [22]:
df["children"].value_counts()

children
0    573
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

## Smoker Column Analysis

In [27]:
df["region"].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

## Region Column Analysis

In [28]:
df["region"].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

## Charges Column Analysis

In [29]:
df["charges"].value_counts()

charges
16884.92400    1
1725.55230     1
4449.46200     1
21984.47061    1
3866.85520     1
              ..
10600.54830    1
2205.98080     1
1629.83350     1
2007.94500     1
29141.36030    1
Name: count, Length: 1337, dtype: int64

## Remove Duplicate Records

In [30]:
df. drop_duplicates(inplace=True)

## Check Dataset Shape After Removing Duplicates

In [31]:
df.shape

(1337, 7)

## Save Cleaned Dataset

In [32]:
df.to_csv("cleaned_data.csv", index=False)